{
 "title": "HW-10.3",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100-(node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"})/4*100"
    }
   ]
  },
  {
   "title": "Free Memmory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sdb\", fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/mnt\"}"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "LA1"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "LA5"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "LA15"
    }
   ]
  }
 ]
}